### ISSUE TITLE
Octree ray cast

### ISSUE THREAD

**Issue by mghabboun** [BioHaskell/octree#5]
Hello, 

I would like to add ray casting for octree, this is a very common operation especially for ray tracing, and I find haskell lacking any implementation for this algorithm. It is not that trivial, is this feature appropriate for this library ? If so I would like to fork and implement it.

Thanks.

**Comment by mgajda** [comment]
Absolutely appropriate!

There are valid uses for raycasting in the spatial search, so please go on implementing it, and do not hesitate to contact me again if you need help!

**Comment by mgajda** [comment]
I assume that you found another way around the problem, so closed.
